-- Baseline migration (no schema changes)
-- Purpose: establish version control starting point
-- Timestamp: <auto-generated by CLI>
-- Notes: intentionally does nothing; safe to apply multiple times in fresh envs

DO $$
BEGIN
  -- no-op
END
$$;
